workInfo:
  title: "Puji Tuhan Sang Pencipta"
  fullTitle: "Puji Tuhan Sang Pencipta"
  composer: "Henri Yulianto"
  workId: "bwv10001"
  movementName: "Exercise"
  externalURL: ""

files:
  svgPath: "bwv10001_optimized.svg"
  notesPath: "bwv10001_json_notes.json"
  audioPath: "bwv10001.mp3"
  
musicalStructure:
  totalDurationSeconds: 21
  totalBars: 8
  visualLeadTimeSeconds: 0.2

measureHighlighters:
    alternating:
    name: "Alternating Colors"
    type: alternating
    colors: [lightblue, lightgreen, lightyellow, lightpink]
    opacity: 0.25



